spring:
  profiles:
    active:
# Тут перечислены доступные настройки для авторизации. Чтобы активировать какой-то тип, достаточно его раскомментировать
# Важно! Должен быть активен только один профиль!
    - basic-auth
#    - form-auth